# Generated by Django 3.2.5 on 2021-08-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='my_image')),
                ('age', models.CharField(choices=[('Child', 'Child'), ('Teenager', 'Teenager'), ('Adult', 'Adult'), ('Senior Adult', 'Senior Adult')], default='Child', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100)),
            ],
        ),
    ]
